action.configuration.email_login_info:
  type: action_configuration_default
  label: 'Email login info'

action.configuration.pass_reset:
  type: action_configuration_default
  label: 'Email password reset link'

action.configuration.welcome_email:
  type: action_configuration_default
  label: 'Welcome email'

action.configuration.send_custom_email:
  type: action_configuration_default
  label: 'Send custom email'