spt_table:
  -
    status: '1'
    pages: /home
    theme: neuronet_home
    roles:
      anonymous: anonymous
      authenticated: authenticated
      administrator: administrator
      alumni: alumni
      deputy_admin: deputy_admin
      current_student: current_student
      glossary_editor: glossary_editor
    weight: '-10'
    remove: Remove
